Análisis de Caso
LIBRERÍA NUMPY

"Aplicando NumPy en Análisis de Datos"
Para optimizar la manipulación de datos se pretende aplicar NumPy, así mejorando eficiencia en cálculos financieros y facilitando la toma de decisiones.

Algunas operaciones que se deben abarcar son:
- Creación y manipulación de arrays multidimensionales.
- Aplicación de funciones estadísticas y matemáticas sobre los datos.
- Indexación y selección eficiente de elementos dentro de los arrays.
- Optimización del rendimiento computacional mediante el uso de broadcasting y operaciones vectorizadas.

El primer paso es crear la matriz de datos utilizando la librería NumPy.
Se fija una semilla (42) para posterior reproducción y obtener igual datos.
Los datos se generan con un randomm entre valores de 100 y 500 para obtener un buen rango de variabilidad de datos.

In [14]:
import numpy as np

# Fijar semilla para reproducibilidad del ejercicio
np.random.seed(42)

# Generar datos simulados (los precios variarán entre 100 y 500)
precios = np.random.uniform(100, 500, size=(5, 5))

print("Matriz de precios:\n", precios)

Matriz de precios:
 [[249.81604754 480.28572256 392.79757672 339.46339368 162.40745618]
 [162.39780813 123.23344487 446.47045831 340.4460047  383.22903112]
 [108.23379772 487.96394086 432.97705632 184.93564427 172.72998688]
 [173.36180394 221.69689718 309.90257265 272.77800746 216.49165608]
 [344.74115789 155.79754426 216.85785941 246.54473732 282.42799369]]


Para obtener el promedio de cada acción durante los 5 días se utiliza el axis=1 y así recorre cada acción.
Al igual para obtener los máximos y mínimos de cada acción se usa la instrucción axis=1.

In [17]:
promedio = np.mean(precios, axis=1)
maximo = np.max(precios, axis=1)
minimo = np.min(precios, axis=1)

print("Promedio por acción:", promedio)
print("Máximo por acción:", maximo)
print("Mínimo por acción:", minimo)

Promedio por acción: [324.95403934 291.15534943 277.36808521 238.84618746 249.27385851]
Máximo por acción: [480.28572256 446.47045831 487.96394086 309.90257265 344.74115789]
Mínimo por acción: [162.40745618 123.23344487 108.23379772 173.36180394 155.79754426]


Para obtener la variación porcentual diaria se usa la fórmula de ((Valor Final-Valor Inicial)/Valor Inicial)x100 que se ve expresada como la diferencia del primer y último día de cada acción y en valor porcentual de 0-1 en valores positivos o negativos según corresponda.

In [18]:
variacion = np.diff(precios, axis=1) / precios[:, :-1]

print("Variación porcentual diaria:\n", variacion)

Variación porcentual diaria:
 [[ 0.92255753 -0.18215854 -0.13578033 -0.52157594]
 [-0.24116313  2.62296501 -0.23747249  0.12566758]
 [ 3.50842483 -0.11268637 -0.57287426 -0.06599949]
 [ 0.27881051  0.39786608 -0.11979431 -0.2063449 ]
 [-0.54807385  0.39192091  0.13689556  0.1455446 ]]


La función np.log permite obtener los algoritmos de cada valor de los 5 días de cada acción.

In [5]:
log_precios = np.log(precios)
print(log_precios)

[[4.9232894  5.2733658  5.1544435  5.07433502 4.75015208]
 [4.75013122 4.66162954 5.22906168 5.07587045 5.14053577]
 [4.62554568 5.28315797 5.21082004 4.79772183 4.77223001]
 [4.77356565 4.8707924  5.02700487 4.96420386 4.86076477]
 [5.08255457 4.73575437 4.86147354 4.9173218  4.9809112 ]]


Con la funcióm np.exp se obtiene el valor exponencial de cada cada, en este caso se están dividiendo en 100 para que la expresión en output no sean tan grandes y evitar extra consumo de memoria.

In [21]:
exp_precios = np.exp(precios / 100)  # escalado para evitar overflow
print(exp_precios)

[[ 12.16010456 121.85809666  50.80403432  29.80374142   5.07372145]
 [  5.07323196   3.42922555  86.89535539  30.09803981  46.16815668]
 [  2.9515722  131.58320756  75.92686415   6.35572793   5.62544395]
 [  5.66109898   9.17946544  22.17633494  15.29888691   8.71387481]
 [ 31.41896146   4.74919648   8.74584381  11.768746    16.84880841]]


Los valores de las acciones son normalizados con la función de mínimo y máximo de cada precio. 

In [22]:
min_vals = precios.min(axis=1, keepdims=True)
max_vals = precios.max(axis=1, keepdims=True)

normalizados = (precios - min_vals) / (max_vals - min_vals)

print("Datos normalizados:\n", normalizados)

Datos normalizados:
 [[0.27497505 1.         0.72477469 0.5569929  0.        ]
 [0.12116299 0.         1.         0.67199161 0.80434967]
 [0.         1.         0.85519484 0.20199041 0.16984743]
 [0.         0.35399752 1.         0.72810637 0.31587527]
 [1.         0.         0.32316686 0.48028717 0.67020233]]


Para obtener el valor específico de algún día para una acción se usa la indexación avanzada, donde se puede escoger en eje X la acción y en eje Y el día.
En este caso, como ejemplo, se usa [2,3] que quiere decir la acción 3 en el día 4 (recordar que en Python las matrices y valores comienzan en 0).

In [23]:
precio_especifico = precios[2, 3]
print("Precio específico:", precio_especifico)

Precio específico: 184.93564427131048


Otro método de indexación avanzada que permite ver varias acciones durante varios días o incluso la misma acción en distintos días:

In [28]:
acciones = [0, 2, 4]
dias = [1, 3, 4]

seleccion = precios[acciones, dias]
print("Selección avanzada:", seleccion)

Selección avanzada: [480.28572256 184.93564427 282.42799369]


Un ejemplo de Broadcasting es este que permite ajustar los valores de todas las acciones en todos los días a una inflación general, como ejemplo se utiliza una inflación de 2% (lo que es lo mismo que representarlo de la forma 1.02).

In [34]:
inflacion = 1.02
precios_ajustados = precios * inflacion
print(precios_ajustados)

[[254.81236849 489.89143702 400.65352826 346.25266155 165.6556053 ]
 [165.6457643  125.69811376 455.39986748 347.25492479 390.89361174]
 [110.39847367 497.72321968 441.63659745 188.63435716 176.18458662]
 [176.82904002 226.13083513 316.10062411 278.23356761 220.8214892 ]
 [351.63598105 158.91349515 221.1950166  251.47563206 288.07655356]]


En el siguiente ejemplo de Broadcasting, se le resta el promedio de los 5 días de cada acción al valor de cada acción de todos los días.

In [37]:
precios_centrados = precios - promedio[:, np.newaxis]
print(precios_centrados)

[[ -75.1379918   155.33168323   67.84353739   14.50935434 -162.54658316]
 [-128.75754129 -167.92190456  155.31510888   49.29065527   92.07368169]
 [-169.13428749  210.59585565  155.60897111  -92.43244094 -104.63809833]
 [ -65.48438352  -17.14929028   71.05638519   33.93181999  -22.35453138]
 [  95.46729938  -93.47631425  -32.4159991    -2.7291212    33.15413517]]
