LIBRERÍA NUMPY PARTE 1
Ejercicio 1 Manipulando Datos Con NumPy Sin Bucles

In [3]:
import numpy as np
valores=np.arange(100)
print(valores)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [5]:
matriz=valores.reshape([10,10])
print(matriz)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [ ]:
zirtam=matriz.T
print(zirtam)

[[ 0 10 20 30 40 50 60 70 80 90]
 [ 1 11 21 31 41 51 61 71 81 91]
 [ 2 12 22 32 42 52 62 72 82 92]
 [ 3 13 23 33 43 53 63 73 83 93]
 [ 4 14 24 34 44 54 64 74 84 94]
 [ 5 15 25 35 45 55 65 75 85 95]
 [ 6 16 26 36 46 56 66 76 86 96]
 [ 7 17 27 37 47 57 67 77 87 97]
 [ 8 18 28 38 48 58 68 78 88 98]
 [ 9 19 29 39 49 59 69 79 89 99]]


In [7]:
zirtamm=zirtam*2
print(zirtamm)

[[  0  20  40  60  80 100 120 140 160 180]
 [  2  22  42  62  82 102 122 142 162 182]
 [  4  24  44  64  84 104 124 144 164 184]
 [  6  26  46  66  86 106 126 146 166 186]
 [  8  28  48  68  88 108 128 148 168 188]
 [ 10  30  50  70  90 110 130 150 170 190]
 [ 12  32  52  72  92 112 132 152 172 192]
 [ 14  34  54  74  94 114 134 154 174 194]
 [ 16  36  56  76  96 116 136 156 176 196]
 [ 18  38  58  78  98 118 138 158 178 198]]


In [8]:
diagonal=np.diag(zirtamm)
print(diagonal)

[  0  22  44  66  88 110 132 154 176 198]


In [9]:
identitty=np.eye(10)
print(identitty)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [10]:
ultimatriz=zirtamm@identitty
print(ultimatriz)

[[  0.  20.  40.  60.  80. 100. 120. 140. 160. 180.]
 [  2.  22.  42.  62.  82. 102. 122. 142. 162. 182.]
 [  4.  24.  44.  64.  84. 104. 124. 144. 164. 184.]
 [  6.  26.  46.  66.  86. 106. 126. 146. 166. 186.]
 [  8.  28.  48.  68.  88. 108. 128. 148. 168. 188.]
 [ 10.  30.  50.  70.  90. 110. 130. 150. 170. 190.]
 [ 12.  32.  52.  72.  92. 112. 132. 152. 172. 192.]
 [ 14.  34.  54.  74.  94. 114. 134. 154. 174. 194.]
 [ 16.  36.  56.  76.  96. 116. 136. 156. 176. 196.]
 [ 18.  38.  58.  78.  98. 118. 138. 158. 178. 198.]]
