EVALUACIÓN MÓDULO 4
PREPARACIÓN DE DATOS

Felipe Ramos Jeria - 10-04-2026

Lección 1: la librería NumPy
- Se crea un conjunto de datos usando NumPy y se usan operaciones básicas para la preparación inicial.

1. Para generar los datos se importa la librería numpy.
2. Se fija una semilla para reproducir los valores (elegí el valor 50 de forma aleatoria).
3. Se solicita crear un datasets de clientes y transacciones usando arrays, para esto el número de clientes (n_clientes) se fija en 20.
4. Los clientes tienen un ID (el número de cliente) y se les asigna una edad random dentro de un rango de 18 a 50 años.
5. Se asigna un valor de cantidad de transacciones a cada cliente dentro de un rango de 1 a 40.
6. Se genera un monto random de cantidad total de dinero gastado para cada cliente, para claridad del ejercicio se asumirá que está en pesos chilenos (CLP).
7. Luego se juntan todos los datos en un array.

In [1]:
import numpy as np

np.random.seed(50)

n_clientes = 20

#De forma opcional, se les asigna un "ID" a los clientes, para mayor orden
clientes_id = np.arange(1, n_clientes + 1)
edades = np.random.randint(18, 50, n_clientes)
transacciones = np.random.randint(1, 41, n_clientes)
montos = np.random.randint(10000, 500000, n_clientes)

#Generación de matriz
data = np.array([clientes_id, edades, transacciones, montos]).T

Para satisfacer el uso de operaciones básicas se usa:
- sum(montos) para sumar los montos totales de los 20 clientes en conjunto.
- mean(montos) para obtener el promedio de los montos y mean(edades) para obtener el promedio de las edades de los 20 clientes.
- len(clientes_id) hace un conteo de la cantidad de clientes en base a sus ID.
- max(montos) y min(montos) para obtener el mayor y el menor de los montos de las transacciones.

In [2]:
total_montos = np.sum(montos)

promedio_montos = np.mean(montos)
promedio_edad = np.mean(edades)

total_transacciones = np.sum(transacciones)

conteo_clientes = len(clientes_id)

max_gasto = np.max(montos)
min_gasto = np.min(montos)

print("Total montos:", total_montos)
print("Promedio montos:", promedio_montos)
print("Promedio edad:", promedio_edad)
print("Total transacciones:", total_transacciones)
print("Cantidad clientes:", conteo_clientes)
print("Mayor gasto:", max_gasto)
print("Menor gasto:", min_gasto)

Total montos: 4073710
Promedio montos: 203685.5
Promedio edad: 29.55
Total transacciones: 419
Cantidad clientes: 20
Mayor gasto: 454318
Menor gasto: 32126


Se guarda el dataset generado en un archivo .npy

In [6]:
np.save("clientes_data.npy", data)

Y también permite cargar el dataset con el comando load()
Con print() se da un vistazo a los primeros datos.

In [5]:
data_cargada = np.load("clientes_data.npy")
print(data_cargada[:10])

[[     1     34     36  64083]
 [     2     18     29 142874]
 [     3     29     28 196352]
 [     4     31     27  32126]
 [     5     19     27 368323]
 [     6     48      7  87824]
 [     7     22     21 156525]
 [     8     24     32 138221]
 [     9     23     22 228718]
 [    10     24      1 125712]]


La otra opción es convertir el dataset a una lista para usar con la librería Pandas.

In [8]:
data_lista = data.tolist()
print(data_lista[:5])

[[1, 34, 36, 64083], [2, 18, 29, 142874], [3, 29, 28, 196352], [4, 31, 27, 32126], [5, 19, 27, 368323]]


Lección 2: la librería Pandas
 Exploración y transformación de datos generados en Lección 1.

- Se carga el .npy de la Lección 1.

In [10]:
import numpy as np
import pandas as pd

data=np.load("clientes_data.npy")

df = pd.DataFrame(data, columns=["cliente_id", "edad", "transacciones", "monto"])

print(df.head())

   cliente_id  edad  transacciones   monto
0           1    34             36   64083
1           2    18             29  142874
2           3    29             28  196352
3           4    31             27   32126
4           5    19             27  368323


La exploración inicial cuenta con:
1. Visualización de primeras head() y últimas filas tail().
2. Obtención de estadísticas descriptivas describe() e info().
3. Aplicación de filtros condicionales.
 - Clientes con gastos superiores a los $300.000
 - Clientes con más de 15 transacciones
 - Clientes menores de 30 años y gastos superiores a $200.000
 - Gasto promedio por transacción


In [11]:
print(df.head())
print(df.tail())

   cliente_id  edad  transacciones   monto
0           1    34             36   64083
1           2    18             29  142874
2           3    29             28  196352
3           4    31             27   32126
4           5    19             27  368323
    cliente_id  edad  transacciones   monto
15          16    44             36  343980
16          17    25             27  162728
17          18    33              3  245611
18          19    22             13  453566
19          20    32             33  216910


In [13]:
print(df.describe())
print(df.info())

       cliente_id       edad  transacciones          monto
count    20.00000  20.000000      20.000000      20.000000
mean     10.50000  29.550000      20.950000  203685.500000
std       5.91608   9.450564      11.623366  139403.130132
min       1.00000  18.000000       1.000000   32126.000000
25%       5.75000  22.750000      11.500000   99013.250000
50%      10.50000  27.000000      24.500000  159626.500000
75%      15.25000  33.250000      29.500000  270203.250000
max      20.00000  49.000000      36.000000  454318.000000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cliente_id     20 non-null     int64
 1   edad           20 non-null     int64
 2   transacciones  20 non-null     int64
 3   monto          20 non-null     int64
dtypes: int64(4)
memory usage: 772.0 bytes
None


In [14]:
clientes_altos = df[df["monto"] > 300000]
print(clientes_altos.head())

    cliente_id  edad  transacciones   monto
4            5    19             27  368323
11          12    31             20  454318
12          13    23              3  445866
15          16    44             36  343980
18          19    22             13  453566


In [15]:
clientes_frecuentes = df[df["transacciones"] > 10]
print(clientes_frecuentes.head())

   cliente_id  edad  transacciones   monto
0           1    34             36   64083
1           2    18             29  142874
2           3    29             28  196352
3           4    31             27   32126
4           5    19             27  368323


In [16]:
segmento = df[(df["edad"] < 30) & (df["monto"] > 200000)]
print(segmento.head())

    cliente_id  edad  transacciones   monto
4            5    19             27  368323
8            9    23             22  228718
12          13    23              3  445866
18          19    22             13  453566


In [17]:
# Gasto promedio por transacción
df["gasto_promedio"] = df["monto"] / df["transacciones"]

print(df.head())

   cliente_id  edad  transacciones   monto  gasto_promedio
0           1    34             36   64083     1780.083333
1           2    18             29  142874     4926.689655
2           3    29             28  196352     7012.571429
3           4    31             27   32126     1189.851852
4           5    19             27  368323    13641.592593


Para guardar el nuevo dataframe en formato CSV se usa df.to_csv()

In [19]:
df.to_csv("clientes_preprocesados.csv", index=False)

Lección 3: Obtención de datos desde archivos
 Se integran los datos de ambas fuentes (CSV) y se unifican en un nuevo dataframe.

1. Se carga el CSV de la Lección 2.

In [20]:
df_clientes = pd.read_csv("clientes_preprocesados.csv")
print(df_clientes.head())

   cliente_id  edad  transacciones   monto  gasto_promedio
0           1    34             36   64083     1780.083333
1           2    18             29  142874     4926.689655
2           3    29             28  196352     7012.571429
3           4    31             27   32126     1189.851852
4           5    19             27  368323    13641.592593
